export const FETCH_TASK = 'FET_TASK'
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS'
export const FETCH_TASK_FAIL = 'FETCH_TASK_FAIL'

export const FILLTER_TASK = 'FILLTER_TASK'
export const FILLTER_TASK_SUCCESS = 'FILLTER_TASK_SUCCESS'
export const FILLTER_TASK_FAIL = 'FILLTER_TASK_FAIL'